# Generated by Django 5.2 on 2025-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videolecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс')], default='5-6', max_length=5, verbose_name='Класс'),
        ),
    ]
