# Generated by Django 5.2 on 2025-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_question_difficulty_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Лимит времени (мин)'),
        ),
    ]
