# Generated by Django 5.2 on 2025-05-11 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lecture_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы за ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Объяснение'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов'), ('text', 'Текстовый ответ')], default='single', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Имеет варианты'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videolecture',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='videolecture',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='videolecture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс')], default='1', max_length=5, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='TestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.test')),
            ],
            options={
                'verbose_name': 'Вариант теста',
                'verbose_name_plural': 'Варианты тестов',
                'ordering': ['test', 'order'],
                'unique_together': {('test', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Баллы')),
                ('max_score', models.PositiveIntegerField(verbose_name='Максимальный балл')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, verbose_name='Детали результатов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testvariant')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.testvariant', verbose_name='Вариант'),
        ),
    ]
