# Generated by Django 5.2 on 2025-05-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_testresult_variant_remove_question_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Баллы'),
        ),
    ]
