# Generated by Django 5.2 on 2025-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_test_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Изображение'),
        ),
    ]
