# Generated by Django 5.2 on 2025-05-13 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='points',
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения (0 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Тест'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order', 'test'], name='core_questi_order_3ad50a_idx'),
        ),
    ]
